before_install:
  - gem install bundler -v 1.12.5
script: "bundle exec rake spec:adapters"
language: ruby
bundler_args: --without coverage --binstubs
sudo: false
cache: bundler
rvm:
  - 2.3.1
  - 2.2.2
  - 2.1.6
