script: "rspec spec"
language: ruby
bundler_args: --without coverage
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-2.2.1
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.2.1
